sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
git:
  submodules: false
cache:
  yarn: true

install:
  - git submodule init
  - yarn submodule
  - yarn
jobs:
  include:
    - stage: build packages
      script:
        - ./build-script.sh
deploy:
  provider: releases
  api_key:
    # [hint] travis encrypt --com -r ddickson/react-icons "********"
    secure: "grtTTtGinvPgGVw9lrTwTi1GTtyJNG+IyqcOD+sFCjWz4I26yuQ96UnNo5QSD3IX1atsOR9MZNNF/UhxYnPUBlTV/FAfrf/cbVmRLFT0so00ZHa8PZC1oLmt4EvSl4gDk3Es8GGbVic1y3CGySpttEumGfQcXwFTB6/l7khOcD9OVxVqeHpcCzwleTOxY1IdnsjZ+247cFOVBHoJeN914H2uWuwaCeHikiJzKFnaUhnIE1IbWKCww57NYXiHBb/RidDGprjnxCiKt+KfbyS7xWRE8ubWTBWCdWtUMy6Z02dDqmTN0dtLOCEGMe3Dnk65+Wh9lhTCCrosu+45deVbWSgPYPoK2gG6I0fWK8OBS7+RYcfuqvttWpE8bmIUBjkoLqeF0xXlcUrpodcyKCzSm5eAbvWCv+6/+PmZf8ER+fwhThuEnO9MlHLjEu4+KzEZkPAFxjPR4jRZYjx4Nwmgas5AJbCgL+Oekgd1GkUtueXiFsuR0QKVwLjNAECK0egDOODunD7D7vtqiIA9C+oclpj7sEwLO4TSlx0Zlk1E4CLJ5xfmNwzseFSk5yVekN8qVMCTVmZdnh+cI9IaLcxI4NRrPj2/DNTQqo2S6zBoU1yGeFAE43A7vUoxZcunZw3JxSsZ6BPvnZSGRfEebvqzoE/6Sbv0E8RUmb7CeTCCk3I="
  file_glob: true
  file: "packages/react-icons/react-icons-*.tgz"
  skip_cleanup: true
