sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
git:
  submodules: false
cache:
  yarn: true

install:
  - git submodule init
  - yarn submodule
  - yarn
jobs:
  include:
    - stage: build packages
      script:
        - ./build-script.sh
deploy:
  provider: releases
  api_key:
    # [hint] travis encrypt --com -r ddickson/react-icons "********"
    secure: "mn3hwGTMXgssdnVTYNQWwJ6a/ZxNm0+sXtKIFqs7FvoZvSi7MQ8ffeD58aPHj1REkSI/6m1f5uh4ApLVUnAPddsEfsnZ6nV333jwq352kFJ09DPhOS/JAXERZcFnVjYJCQJDiOhbIEZENVSCfabKaJSAkoef6tWQ8GArHIhWMRqCDVLB/n277ZjdB1eztpslnQTS0xmoB0wOsbxEmnIW224Ow6J2fS29429UKYW3Rhs0LHMuIHxB5pp1MuflBCVFgsC0myU4jBKdT9oyH8TIe8sjkRGf874M22dhMcPr+V1yTLKGe/JkHesVST+FpfzaLgm+Uvlt1gVAZK9ZdFPO1fYKvc9SfRZxJuQMtJ/TCUQ+Jx2rVzpw3xLvqDa7JaqKeE8TmZDsUKy27LsH+3XXdCO2dbMMQgIMj3+rxBfOe3ATgl1PeobfJ4pGFd4CsOQ5uentPYShlgCViMygD8EPy2Sso+oYhXum8wMSVdGGnn3/dOzE8w4d8Y/2JLpqp5KGN2viGHlsUVIjqvkHFGkrxGC/V/2ciJYFUVhPPx0G9uiFSKm1R9F5BXpAXEIqMILz1OuriT8v3ICpnqb/GvOLpHGt5DWFpi2v3ryJXaEB0y672rRvtqGDW46ucckjhvgZukuj1zczKozpMTikiCTxfDl4ORxGSkon2JkLq4iahgQ="
  file_glob: true
  file: "packages/react-icons/react-icons-*.tgz"
  skip_cleanup: true
  on:
    tags: true
